spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application:
    name:microcloud-config-client
server:
  port: 8201           #Eureka服务端口
eureka:
  client:
    service-url:
      defaultZone:http://edmin:hello@eureka-7001.com:7001/eureka,http://edmin:hello@eureka-7002.com:7002/eureka,http://edmin:hello@eureka-7003.com:7003/eureka   #######*******HA集群配置

---
spring:
  profiles: beta
  application:
    name:microcloud-config-client
server:
  port: 8102         #Eureka服务端口
  
eureka:
  client:
    service-url:
      defaultZone:http://edmin:hello@eureka-7001.com:7001/eureka,http://edmin:hello@eureka-7002.com:7002/eureka,http://edmin:hello@eureka-7003.com:7003/eureka   #######*******HA集群配置